jobs:
  build:
    name: Make gitartwork SVG
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@v3
    - uses: jasineri/gitartwork@v1
      with:
        text: KOCADOR
        user_name: kabasilim
    - uses: jasineri/simple-push-action@v1
name: gitartwork from a contribution graph
'on':
- workflow_dispatch
permissions: write-all
